version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24
  pre_build:
    commands:
      - corepack enable
      - corepack prepare pnpm@latest-10 --activate
      - pnpm install
  build:
    commands:
      - pnpm run build

cache:
  paths:
    - 'node_modules/**/*'

artifacts:
  base-directory: dist
  files:
    - '**/*'
